config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'houses#index'
  resources :houses do
    collection { post :import }
      collection do
        get 'search'
      end
  end
end

app/models/house.rb
class House < ActiveRecord::Base
  searchkick

  def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
    House.create! row.to_hash
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def search
    if params[:search].present?
      @houses = House.search(params[:search])
    else
      @houses = House.all
    end
  end

  def index

  end

  def show

  end

  def new
    @houses = House.new
  end

  def create
    @houses = House.new(house_params)
  end

  def import
    House.import(params[:file])
    redirect_to houses_path, notice: "Houses added Successfully"
  end

  private

  def house_params
    params.require(:house).permit(
    :address,
    :city,
    :state,
    :zipcode,
    :size,
    :price
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/houses/index.html.erb
<div class="module">
  <br />
  <br />
  <br />
  <h1 class="text-center" style="color: white">Whichouse.ify</h1>
  <h2 class="text-center" style="color:white"> The Journey to your next house! </h2>
  <%= form_tag search_houses_path, method: :get, class: "body-form body-center", role: "search" do %>
  <br />
  <br />
  <br />
  <div class="text-center">
    <p>
      <%= text_field_tag :search, params[:search], class: "align-center" %>
      <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
    </p>
    <% end %>
  </div>
</div>

<footer class="row">
  <div class="large-10 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p> © Copyright no one at all. Go to town.</p>
      </div>
      <div class="large-12 columns">
        <ul class="form-inline">
          <a class="inline" href="#">About</a>
          <a class="inline" href="#">Careers</a>
          <a class="inline" href="#">Site Map</a>
          <a class="inline" href="#">Mission</a>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/houses/new.html.erb
<h1> New Houses </h1>

<% if @houses.errors.any? %>
  <h2> Error! </h2>
  <ul>
  <% @houses.errors.full_messages.each do |error_msg| %>
  <li>
    <%= error_msg %>
  </li>
  <% end %>
  </ul>
<% end %>

<h3> Import Houses </h3>
<%= form_tag import_houses_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Houses" %>
  <% end %>

app/views/houses/search.html.erb
<h1> House Listings</h1>

<div class="row">
  <% @houses.each do |house| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <li><%= house.address %>, <%= house.city %></li>
    </div>
  </div>
  <% end %>
</div>

app/views/houses/show.html.erb
<h1> House Listings</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhichHouseApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>